config/routes.rb
Backbone::Application.routes.draw do
  resources :teams
  resources :games

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :home_team, :away_team

  belongs_to :home_team, :class_name => :Team
  belongs_to :away_team, :class_name => :Team
end

app/models/pairing.rb
class Pairing < ActiveRecord::Base
  attr_accessible :game, :home_team, :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :country, :name
  
  has_many :home_games, :class_name => :Game, :foreign_key => :home_team_id
  has_many :away_games, :class_name => :Game, :foreign_key => :away_team_id

  def games 
    home_games + away_games
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :provider, :uid
  attr_accessible :provider, :uid, :name, :email

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json

  def index
    respond_with(@games = Game.all)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  respond_to :json

  def index
    respond_with(@teams = Team.all)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.haml
#shell

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "EM2012", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      Logged in as #{current_user.name}
    %li
      = link_to('Logout', signout_path)
  - else
    %li
      = link_to('Login', signin_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Backbone"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row-fluid
            .span12
              = render 'layouts/messages'
              = yield
          %footer